### ISSUE TITLE
Ship up-to-date versions of SNAP plugins with WOIS

### ISSUE THREAD

**Issue by j08lue** [TIGER-NET/WOIS_Installer#1]
When fresh SNAP installation is started and you go to Tools > Plugins and check for updates you will notice that many modules are being updated. Since WOIS is often run in places with very bad internet connection it is a good idea to include those updated modules in the installer. In SNAP the modules go in C:\Program Files\snap\snap\modules, C:\Program Files\snap\s1tbx\modules, C:\Program Files\snap\s2tbx and C:\Program Files\snap\s3tbx and you can just check which jar files have newer dates and pick them. During the installation I think it should be enough to just copy the jar's into the correct directory but maybe double check that.

**Comment by j08lue** [comment]
@radosuav I am unsure if it is that simple. When I log what SNAP Desktop does when you click on "Update", there are two steps:

First, SNAP just downloads a bunch of files. These are mostly NetBeans `.nbm` files rather than `.jar` files:
https://gist.github.com/j08lue/139fa67932c59845894620e220c83208#file-esa-snap-2-plugin-update-before-restart-log

Second, SNAP asks to restart and automatically runs a NetBeans update manager after the restart that makes the following changes:
https://gist.github.com/j08lue/139fa67932c59845894620e220c83208#file-esa-snap-3-plugin-update-after-restart-log
which includes the `.jar` files you mentioned. In my case these are stored in `C:\Users\josl\AppData\Roaming\SNAP\modules\`, but also a bunch of other things, like updating some xml files. 

It should be possible to run the same NetBeans updater with files that we provide (I found [some old NetBeans blog post about this](https://blogs.oracle.com/NetBeansSupport/entry/how_to_download_and_install)). But it would take a while to find out how.

Could we perhaps just make sure we regularly update the SNAP version shipped with the WOIS installer, so people get the most recent version when they install the package? I don't know, however, how often [ESA/STEP](http://step.esa.int/main/download/) updates their installer binaries...

**Comment by radosuav** [comment]
You are right, the downloaded files are .nbm. On my machine they were saved to C:\Program Files\snap\snap\update\download, C:\Program Files\snap\s1tbx\update\download, etc.  Also, it seems that SNAP runs the NetBeans updater on startup if any of those directories exist. So a possible solution would be to create those directories before SNAP installation (and copy nmb files into them) and instruct the user to select "Run SNAP" in the last step and then close it to continue with installation of the next WOIS component. 

The module updates appear much more frequently then SNAP releases so even if you get a latest SNAP binary it is likely that the included modules won't be the newest.

**Comment by j08lue** [comment]
I am currently not planning to fix this - that is to include updated SNAP modules with the installer.

But that can change if someone should tell me that this is important... (@radosuav)

**Comment by radosuav** [comment]
If nobody is complaining then I guess it's fine as is. But if a bug concerning SNAP functionality is reported then it might be worth checking if newer modules provide a fix.
