### ISSUE TITLE
GRASS 6 folder wrongly configured in processing

### ISSUE THREAD

**Issue by ctottrup** [TIGER-NET/WOIS_Installer#12]
GRASS 6 folder wrongly configured in processing -> options -> providers. Points to GRASS 7

**Comment by j08lue** [comment]
This is actually very easy to change in these lines: https://github.com/TIGER-NET/WOIS_Installer/blob/07d1cf78d60d47a867dcf657932833a7df60281a/woisInstaller.py#L652-L657

@ctottrup But is GRASS 7 needed at all for WOIS? We could also just omit it from the installer and then GRASS6 would be set automatically.

**Comment by j08lue** [comment]
Fixed with commit https://github.com/TIGER-NET/WOIS_Installer/commit/b49702955a3a2028a89c0701b364a96a145f8798

The GRASS folder is now set to the highest **GRASS 6** version (`C:\OSGeo4W64\apps\grass\grass-6.4.3` after default install).
