### ISSUE TITLE
WOIS toolbox is not activated by the installer

### ISSUE THREAD

**Issue by radosuav** [TIGER-NET/WOIS_Installer#16]
In previous versions of WOIS, the WOIS toolbox used to be a equivalent to the workflows plugin. Therefore [this](https://github.com/TIGER-NET/WOIS_Installer/blob/master/woisInstaller.py#L647) used to be sufficient to activate it.

Currently WOIS Toolbox is a collection within the workflows plugin, so the following settings also need to be set:
ACTIVATE_WOIS_TOOLBOX
TASKBAR_BUTTON_WOIS_TOOLBOX

The following should probably be deactivated (not to confuse users):
TASKBAR_BUTTON_WORKFLOW

@j08lue, once this is implemented could you send me the compiled versions of 64 and 32 bit installers and I'll update the installation package.

**Comment by j08lue** [comment]
I thought this was somehow intentional... Thanks for the instructions, which are implemented in https://github.com/TIGER-NET/WOIS_Installer/commit/0e8b7996764e496045f09d8b88311a913acc6eec. Binaries follow.

**Comment by j08lue** [comment]
Sorry this took so long - building and testing on my 32 bit VM...

I now include the binaries with this package at https://github.com/TIGER-NET/WOIS_Installer/tree/master/binaries @radosuav please download from there

**Comment by radosuav** [comment]
Thanks!
