### ISSUE TITLE
OSGeo4W setup does not properly install matplotlib from packages

### ISSUE THREAD

**Issue by j08lue** [TIGER-NET/WOIS_Installer#17]
When running OSGeo4W setup with pre-downloaded packages (and the `--local-install`) option, `matplotlib` *does* get installed:

![image](https://cloud.githubusercontent.com/assets/3404817/22595285/1d4b118c-ea27-11e6-93c6-5e5280092f09.png)

 but OSGeo4W's python cannot find it:

![image](https://cloud.githubusercontent.com/assets/3404817/22595249/f1f5d634-ea26-11e6-969f-c4eb008b0cf5.png)

Only after re-installing it through OSGeo4W setup, it can be found. I re-downloaded the matplotlib package and all packages are at the most recent versions (with QGIS 2.18.3).

@radosuav Do you have any idea why this problem occurs? Does this sound familiar from earlier WOIS installers?

**Comment by j08lue** [comment]
It appears that `C:\OSGeo4W64\apps\Python27\Lib\site-packages\matplotlib-1.3.1-py2.7-win-amd64.egg` is missing in `sys.path`

```python
['C:/Users/wois/.qgis2/python/plugins\\processing_gpf', 'C:/Users/wois/.qgis2/python/plugins\\processing_workflow', 'C:/Users/wois/.qgis2/python/plugins\\processing', 'C:/OSGEO4~1/apps/qgis/./python', u'C:/Users/wois/.qgis2/python', u'C:/Users/wois/.qgis2/python/plugins', 'C:/OSGEO4~1/apps/qgis/./python/plugins', 'C:\\OSGEO4~1\\apps\\Python27\\lib\\site-packages\\setuptools-0.9.8-py2.7.egg', 'C:\\OSGEO4~1\\apps\\orfeotoolbox\\python', 'C:\\OSGEO4~1\\bin', 'C:\\OSGEO4~1\\bin\\python27.zip', 'C:\\OSGEO4~1\\apps\\Python27\\DLLs', 'C:\\OSGEO4~1\\apps\\Python27\\lib', 'C:\\OSGEO4~1\\apps\\Python27\\lib\\plat-win', 'C:\\OSGEO4~1\\apps\\Python27\\lib\\lib-tk', 'C:\\OSGEO4~1\\apps\\Python27', 'c:\\osgeo4~1\\apps\\python27\\lib\\site-packages\\jinja2-2.7.2-py2.7.egg', 'c:\\osgeo4~1\\apps\\python27\\lib\\site-packages\\markupsafe-0.23-py2.7-win-amd64.egg', 'c:\\osgeo4~1\\apps\\python27\\lib\\site-packages\\pytz-2012j-py2.7.egg', 'c:\\osgeo4~1\\apps\\python27\\lib\\site-packages\\shapely-1.2.18-py2.7-win-amd64.egg', 'c:\\osgeo4~1\\apps\\python27\\lib\\site-packages\\xlrd-0.9.2-py2.7.egg', 'c:\\osgeo4~1\\apps\\python27\\lib\\site-packages\\xlwt-0.7.5-py2.7.egg', 'C:\\OSGEO4~1\\apps\\Python27\\lib\\site-packages', 'C:\\OSGEO4~1\\apps\\Python27\\lib\\site-packages\\PIL', 'C:\\OSGEO4~1\\apps\\Python27\\lib\\site-packages\\win32', 'C:\\OSGEO4~1\\apps\\Python27\\lib\\site-packages\\win32\\lib', 'C:\\OSGEO4~1\\apps\\Python27\\lib\\site-packages\\Pythonwin', 'C:\\OSGEO4~1\\apps\\Python27\\lib\\site-packages\\wx-2.8-msw-unicode', u'C:/Users/wois/.qgis2//python']
```
![image](https://cloud.githubusercontent.com/assets/3404817/22595448/cc49569e-ea27-11e6-9763-f18cc90eef52.png)

But why...

**Comment by radosuav** [comment]
WOIS 4.0 (and previous versions) is using matplotlib 1.3.0 because of http://hub.qgis.org/issues/12314. Maybe OSGeo4W thinks that you have 1.3.1 already installed and so doesn't do anything during the local installation of 1.3.0, but when you run setup with "install from internet" option it reinstalls 1.3.1?

**Comment by j08lue** [comment]
Thanks @radosuav!

But no, the offline installer *does* install 1.3.1 from the package I provided - it shows up as installed in OSGeo4W Setup (see first picture [above](https://github.com/TIGER-NET/WOIS_Installer/issues/17#issue-205175093)). The offline installer just does add the matplotlib `egg` to `PYTHONPATH`, only when I choose "re-install" in OSGeo4W Setup.

Do you know how OSGeo4W populates its `PYTHONPATH`? Seems like some script is doing that (and failing for matplotlib).

**Comment by j08lue** [comment]
> Do you know how OSGeo4W populates its PYTHONPATH? Seems like some script is doing that (and failing for matplotlib).

I found the spot: `C:\OSGeo4W64\apps\Python27\Lib\site-packages\easy-install.pth`

If the installer continues to fail with 1.3.0, I will just append the matplotlib egg to that PTH file manually.

**Comment by radosuav** [comment]
Not sure what could be the problem. Maybe something to do with permissions (#8)?

Just make sure that at the end 1.3.0 is installed (not 1.3.1) or there could be issues with some workflow steps (can't remember now which ones).

**Comment by j08lue** [comment]
The installation works out of the box with matplotlib 1.3.0.

Thanks for your help, @radosuav .
