### ISSUE TITLE
GDAL 2.1.3 or 2.1.2?

### ISSUE THREAD

**Issue by j08lue** [TIGER-NET/WOIS_Installer#18]
We would prefer to ship GDAL 2.1.3 with QGIS because of its support for the new Sentinel 2 archive format.

@radosuav do you see problems with this?

**Comment by radosuav** [comment]
It should be quite safe. The only issue that I can foresee is that users will be able to open S2 imaged in the new format in QGIS but might not be able to use them directly in all Processing algorithms (I haven't tested this) which might be confusing. But the advantage of being able to visualize S2 images outweighs this.

**Comment by j08lue** [comment]
Thanks, @radosuav !
