### ISSUE TITLE
Instruct users to install snappy on SNAP install

### ISSUE THREAD

**Issue by j08lue** [TIGER-NET/WOIS_Installer#2]
The SNAP plugin now requires snappy to be installed so remember to instruct the user to do that.

**Comment by j08lue** [comment]
As far as I can see, a `snappy` is already included with the installation package in `SNAP additional modules` and copied to `~/.snap/snap-python` upon install, which is then added to the path [in GPFUtils.py](https://github.com/DHI-GRAS/processing_gpf/blob/9dd69c8e0811680454903e29beba95a7008eb75f/GPFUtils.py#L223).

So there is no need for the user to do anything else during installation, is there, @radosuav ?

If I open QG 2.14.2 and `import snappy` in the Python shell, I get [that IO error you mention](https://github.com/DHI-GRAS/processing_gpf/blob/9dd69c8e0811680454903e29beba95a7008eb75f/GPFUtils.py#L228-L230), but apparently that can be neglected?

**Comment by radosuav** [comment]
I was thinking of instructing the user about this dialog (from SNAP installation):
![screenshot](https://cloud.githubusercontent.com/assets/4759850/15318685/7e712402-1c27-11e6-8042-7b267713c2c5.png)

But I didn't remember that snappy is in "SNAP additional modules". If it's there and it works after being copied then good. In that case I guess that we should tell users not to select "Configure SNAP for use with Python".

**Comment by j08lue** [comment]
I think what that dialogue does is just to run [this bat script](https://github.com/senbox-org/snap-installer/blob/f98c19538526835cf43d2f37ffd9ede3b217caa1/files/winx64/bin/snappy-conf.bat). And that just configures the module and copies it exactly the same place. 

Moreover, the script fails when I run it with OSGeo Python and only works with my Anaconda Python.

So I think, too, it is best not to use that SNAP installer step. I will put an instruction to the user in the WOIS installer.
