### ISSUE TITLE
32 bit installation - C++ warning

### ISSUE THREAD

**Issue by j08lue** [TIGER-NET/WOIS_Installer#21]
Installation on 32 bit Windows 10 is successful: All 56 workflows are available, which means their dependencies are at least loading correctly:

![image](https://cloud.githubusercontent.com/assets/3404817/22838180/4a8dea6e-efc4-11e6-938b-e689f26ee414.png)

However, when QGIS starts, the user gets the following warning shown 5 times!

![image](https://cloud.githubusercontent.com/assets/3404817/22837940/09e546c0-efc3-11e6-97cb-98f6735a7ca6.png)

I do not know which component of QGIS or the plugins is causing this and the proposed solutions I am able to find vary greatly:

- http://gis.stackexchange.com/questions/72506/how-to-fix-runtime-error-r6034-an-application-has-made-an-attempt-to-load-the-c
- https://hub.qgis.org/issues/8942
- http://stackoverflow.com/questions/14552348/runtime-error-r6034-in-embedded-python-application/14680947#14680947

Question is whether QGIS still works and we in that case can ask the 32 bit users to ignore the warning?

**Comment by radosuav** [comment]
Currently we deal with it by providing a solution in the Troubleshooting section (2.6) of the installation guide ;)

**Comment by j08lue** [comment]
Sorry, I did not see that this was already covered. :) But no (new) worries then.
