### ISSUE TITLE
Error code 14001 when running WOIS 4.1 installer

### ISSUE THREAD

**Issue by gforkuor** [TIGER-NET/WOIS_Installer#23]
I have tried installing WOIS 4.1 (64bit) on three different windows machines. In all cases, i get an error message stating: "**Error loading Python DLL: \Temp\.......\python.dll (Error code 14001)**" I have checked the error on Google and applied a number of recommended solutions but the problem persist. I actually had 4.0 running smoothly. Please advice.

**Comment by j08lue** [comment]
@gforkuor Thank you very much for reporting this and sorry for your inconvenience.

We just had this issue a couple of days ago with a similar installer we are making (https://github.com/GlobWetlandAfricaIII/GWA_Installer/issues/2). We found a solution - to use an updated version of `pyinstaller` that creates an executable that is compatible with a wider range of systems (not only recent Windows 10, which we were testing on).

Please download the new installer from here, I hope it now works as it should:
https://github.com/TIGER-NET/WOIS_Installer/raw/master/executables/woisInstaller_x64.exe

Again, sorry for your trouble.

**Comment by gforkuor** [comment]
Dear Jonas,

Many thanks for your response and help. I’ll download the new installer and try again. I’ll revert in case there are more problems.

Regards,

Gerald
