### ISSUE TITLE
GRASS 6 algorithms not working

### ISSUE THREAD

**Issue by j08lue** [TIGER-NET/WOIS_Installer#26]
The recent WOIS and GWA installation packages include both GRASS 6 and GRASS 7 together with QGIS 2.18.9. 

All paths in the Processing Toolbox settings are set correctly
![image](https://user-images.githubusercontent.com/3404817/26935480-5fabe298-4c6c-11e7-8a54-87535aac170b.png)

Despite this, GRASS 6 algorithms cannot be run:

![image](https://user-images.githubusercontent.com/3404817/26935730-0066d95e-4c6d-11e7-9a80-a0143c98a46e.png)

This is a problem particularly due to the widespread use of `r.mapcalculator` in many of the workflows.

**Comment by j08lue** [comment]
The problem strictly speaking has nothing to do with the WOIS installer, because **it also occurs in QGIS installed with standalone OSGeo4W**.

**Comment by j08lue** [comment]
We tried a couple of things:

- [x] Check on clean OSGeo4W QGIS 2.18.9 installation – error exists already here
- [x] Check with QGIS stock processing toolbox (instead of the [WOIS adapted version](https://github.com/DHI-GRAS/WOIS_processing)) – error
- [x] Disable [GRASS’s installation check](https://github.com/qgis/QGIS/blob/release-2_18/python/plugins/processing/algs/grass/GrassUtils.py#L386-L407) – the algorithm can now be executed but it fails (`invalid map`)

**Comment by j08lue** [comment]
The error might have to do with the constellation of packages installed from OSGeo4W, because on some machines with the same versions of GRASS and QGIS but different sets of packages installed, the GRASS 6 algorithms **do work**.

Also, on a machine with QGIS 2.18.7 and about the same packages installed, the error also occurs.

**Comment by radosuav** [comment]
Two most suspect packages would be GDAL and GRASS plugin. On my machine I have the latest version of GDAL (2.2.0) and the GRASS plugin installed but for some reason it fails to load properly. GRASS 6 algorithms execute fine in Processing. 

Maybe check if the problem computers have GRASS plugin installed and loaded and if GDAL is not up to date.

**Comment by j08lue** [comment]
@radosuav you were right that the issue was because of GDAL: The OSGeo4W installer does not automatically include the `gdal110dll` package when installing GRASS 6. @KittelC found out in https://github.com/DHI-GRAS/processing_SWAT/issues/14 that this was the cause of this issue.

So users who have this issue need to install just that package (5 MB download) by running the OSGeo4W setup and selecting the package:

![gdal110](https://user-images.githubusercontent.com/3404817/26970837-080800b8-4d0b-11e7-85ca-f2e4d193e793.png)

We will report this to OSGeo.
