### ISSUE TITLE
SNAP installation problems

### ISSUE THREAD

**Issue by radosuav** [TIGER-NET/WOIS_Installer#27]
Reported by @ewamiti in https://github.com/DHI-GRAS/processing_gpf/issues/46

>@radosuav @j08lue
>I am training a group of participants in WOIS. During the automatic installation all computer did not complete SNAP installtion. This resulted into the following:
>1. WOIS workflow for PG06 on water bodies mapping RADAR does not appear in most computers.
>2. In those computers that it appeared, the processing was not saving the output.
    Kindly help with a solution.

**Comment by radosuav** [comment]
Hi @ewamiti,
Could you please provide more details:
1. Which version of WOIS were you installing?
2. On which operating systems did you install it?
3. What was the problem with the SNAP installation? Did an error message appear? If possible it would be good to have a screenshot of the error message.

For the two results that you report:
1. Those user probably skipped the SNAP post-installation step in WOIS Installer. This step activates the the SNAP algorithm provider in QGIS. If the provider is not activated then the workflows which use SNAP algorithms will not be shown.
2. Those user executed the SNAP post-installation step. However, since SNAP was not installed no actual processing was done when the workflow step was executed and so no output was saved.

**Comment by radosuav** [comment]
Could it be related to https://github.com/TIGER-NET/WOIS_installer/issues/8? Was the installer run as administrator?

**Comment by ewamiti** [comment]
Thank you, We have resolved the problem.
