### ISSUE TITLE
SNAP S1tbx and S2tbx not activated after fresh install

### ISSUE THREAD

**Issue by j08lue** [TIGER-NET/WOIS_Installer#6]
Some modules are not ticked off correctly

**Comment by j08lue** [comment]
Need details on this. Was this the same as the (now closed) https://github.com/DHI-GRAS/ESA_Processing/issues/11?

**Comment by radosuav** [comment]
I think so...

**Comment by j08lue** [comment]
Thanks @radosuav. :-) I will test this in the next days - we are setting up a Windows virtual machine now to be able to test on a clean system each time.

**Comment by j08lue** [comment]
Activating S1tbx and S2tbx **after** a fresh WOIS installation on a clean machine works. So https://github.com/DHI-GRAS/ESA_Processing/issues/11 did fix that part.

But why are they not activated automatically upon installation?

**Comment by j08lue** [comment]
I can see that we in the installer [call](https://github.com/TIGER-NET/WOIS_Installer/blob/master/woisInstaller.py#L239) [this function](https://github.com/TIGER-NET/WOIS_Installer/blob/master/woisInstaller.py#L596):

```
def activateSNAPplugin(self, dirPath):
    self.setQGISSettings("PythonPlugins/processing_gpf", "true")
    self.setQGISSettings("Processing/configuration/ACTIVATE_SNAP", "true")
    self.setQGISSettings("Processing/configuration/SNAP_FOLDER", dirPath)
```

Should this include some QGIS settings call to activate S1tbx and S2tbx?

**Comment by j08lue** [comment]
This was actually not that hard to find. `QSettings.setValue` writes to registry on Windows.

The settings are called

```
S1TBX_ACTIVATE
S2TBX_ACTIVATE
```

in Windows registry `HKEY_CURRENT_USER > SOFTWARE > QGIS > QGIS2 > Processing > Configuration`

![image](https://cloud.githubusercontent.com/assets/3404817/16223810/7f343e22-379f-11e6-8785-8280a5d8bfdc.png)

**Comment by radosuav** [comment]
Sorry, I misread your question in my first answer. But it should be fixed with your latest commit :) The previous version of the installer was written when the processing_gpf plugin included only BEAM and S1TBX and activating the different toolboxes separately was not necessary.

**Comment by j08lue** [comment]
This is fixed.
