### ISSUE TITLE
modifyRamInBatFiles still necessary?

### ISSUE THREAD

**Issue by j08lue** [TIGER-NET/WOIS_Installer#7]
https://github.com/TIGER-NET/WOIS_Installer/blob/master/woisInstaller.py#L233

This step in the BEAM and SNAP installation should limit maximum RAM consumption by setting a flag in the respective option files.

It causes trouble because it needs admin rights - i.e. the installer must be run as administrator, otherwise the installer will just quit without an error message.

Also, it seems not to work safely - even if run as administrator, flags are not set correctly, as far as I can see. There are a lot of things that can break, too, since the `_ram` function needs to query the os for all kinds of stuff https://github.com/TIGER-NET/WOIS_Installer/blob/master/woisInstaller.py#L604.

Do we really need this at all or can it be removed?

**Comment by j08lue** [comment]
I just re-ran the SNAP installation and it seems the SNAP installer already requires admin rights, not just the modification.

**Comment by radosuav** [comment]
WOIS has been installed on a large range of computers with very different amounts of RAM. So the default BEAM and SNAP settings might prevent the software running on some machines while not using the full potential of others. 

However, if this is causing issues now then maybe snap-conf-optimiser.exe (located in C:\Program Files\snap\bin) can somehow be used right after the installation.

Also, removeIncompatibleJavaOptions() can probably be now removed.

**Comment by j08lue** [comment]
Thanks for the clarification, @radosuav . I think pointing the user to the dedicated SNAP and BEAM optimization tools is a good option. 

Should I include a note about this in the installer or should we just add it to the manual?

**Comment by radosuav** [comment]
Just note that as far as I know this tool does not exist for BEAM. And I'm not sure what it actually does for SNAP ;)

Also, this step tool should probably be called automatically in snapPostInstallWindow(), otherwise I think that very few users will read the instructions and perform the optimisation manually.

**Comment by j08lue** [comment]
Hmm, I had hoped that the manual optimization was not crucial for most (modern) systems, only on very limiting hardware or 32 bit.

If optimization _is_ important, I will probably need to put the `.vmoptions` modification back into the installer and fix it up. 

The SNAP optimization tool only calculates the best values for the current amount of free memory but the user needs to add them manually to the .vmoptions files, as far as I can see. And, you are right, BEAM does not even have such a tool.

So I think running the optimization tool as part of the installation is not an option.

What do you reckon we should do?

**Comment by radosuav** [comment]
During TIGER-NET we were installing WOIS on many computers with very limiting hardware or 32 bit ;)

Are there any particular issues with setting the RAM that you have experienced? As far as I remember this always used to work fine, except from running out of memory on 32 bit systems which was fixed by https://github.com/TIGER-NET/WOIS_Installer/commit/df1696efef98cffb8d89457de77bb831ff9f63f2

@hubersi what do you think?

**Comment by j08lue** [comment]
I now put the RAM settings modification back in, since they still are necessary.

The problems I was experiencing was, firstly, the run-as-admin requirement, which however exists not only for this step but for other steps in the installation, too (#8).

Secondly, I had the impression that the function did not work safely, at least for SNAP. I will look further into that and make it work.

Two more questions to that:

### For SNAP

Do the RAM settings only have to be set in `C:\Program Files\snap\bin\gpt.vmoptions` or also in `C:\Program Files\snap\bin\pconvert.vmoptions`?

Or is only the gpt (graph processing tool) used by WOIS?

### For BEAM

Here, there exist three settings files:
1. `C:\Program Files\beam-5.0\bin\gpt.bat`
2. `C:\Program Files\beam-5.0\bin\pconvert.bat`
3. `C:\Program Files\beam-5.0\bin\visat.vmoptions`

and their RAM flags are already set to optimal settings for 64 bit (https://github.com/bcdev/beam/commit/3aee676687c0eabb08b083774c679acc923241c0) during BEAM installation, but not adjusted for 32 bit. Hopefully this will get fixed upstream and in SNAP, too, then we can drop the modification in our script.

Same question here: should the RAM actually be modified in all three of them?

**Comment by radosuav** [comment]
Ok, I was not aware that BEAM and SNAP installers were already setting optimal RAM. Maybe in this case the WOIS installer should only modify RAM for 32 bit installations? Reducing the number of operations performed by the installer (at least for 64 bit machines) is probably a good thing.

WOIS uses only gtp from BEAM and gpt and snappy from SNAP. Snappy RAM usage has not previously been modified but to be consistent maybe the same limit as for gpt should be set? The settings are in C:\Users\user_name.snap\snap-python\snappy.

**Comment by radosuav** [comment]
The last path should be C:\Users\user_name.snap\snap-python\snappy\snappy.ini
