### ISSUE TITLE
Installer must be run as administrator

### ISSUE THREAD

**Issue by j08lue** [TIGER-NET/WOIS_Installer#8]
At least the SNAP installer requires admin rights, perhaps there are other packages as well.

Should we try [this solution to make the installer require admin rights](http://stackoverflow.com/a/19719292)?

Or just include a [simple check](http://stackoverflow.com/a/1026626)?

**Comment by radosuav** [comment]
In the current installation process the user is asked to run the installation as administrator (see section 2.3 of the "WOIS Installation and User Guide"). But it would be nice if this could be enforced automatically. Or at least the installation aborted and user warned if the rights are not sufficient.

**Comment by j08lue** [comment]
Oops RTFM. :-) I will look into including that as an enhancement.

**Comment by j08lue** [comment]
I will revisit this feature for the next major release.
